name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore SkirClient.csproj

      - name: Build
        run: dotnet build SkirClient.csproj -c Release --no-restore -warnaserror

      - name: Test
        run: dotnet test SkirClientTest/SkirClientTest.csproj -c Release --no-build
